// <auto-generated />
using System;
using BookReview.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookReview.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20251117083951_AddedMoreSeedBooks")]
    partial class AddedMoreSeedBooks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookReview.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PublishedYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Italo Calvino",
                            Description = "En poetisk samling av berättelser om tänkta städer.",
                            Genre = "Fiktion",
                            PublishedYear = 1972,
                            Title = "Den osynliga staden"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Stieg Larsson",
                            Description = "Första delen i Millennium-serien.",
                            Genre = "Thriller",
                            PublishedYear = 2005,
                            Title = "Den eviga striden"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Imre Kertész",
                            Description = "En stark berättelse om en ung pojkes upplevelser under Förintelsen.",
                            Genre = "Historisk roman",
                            PublishedYear = 1975,
                            Title = "Mannen utan öde"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Jane Austen",
                            Description = "En tidlös berättelse om kärlek, stolthet och samhällsnormer i 1800-talets England.",
                            Genre = "Klassiker",
                            PublishedYear = 1813,
                            Title = "Stolthet och fördom"
                        },
                        new
                        {
                            Id = 5,
                            Author = "J.K. Rowling",
                            Description = "Den föräldralöse Harry Potter upptäcker på sin elfte födelsedag att han är en trollkarl och börjar på Hogwarts skola för häxkonster och trolldom.",
                            Genre = "Fantasy",
                            PublishedYear = 1997,
                            Title = "Harry Potter och de vises sten"
                        },
                        new
                        {
                            Id = 6,
                            Author = "J.K. Rowling",
                            Description = "Harrys andra år på Hogwarts involverar en mörk hemlighet, en gammal dagbok och en mystisk varelse som attackerar elever.",
                            Genre = "Fantasy",
                            PublishedYear = 1998,
                            Title = "Harry Potter och Hemligheternas kammare"
                        },
                        new
                        {
                            Id = 7,
                            Author = "J.K. Rowling",
                            Description = "Harry får veta att en farlig fånge, Sirius Black, har rymt från trollkarlsfängelset Azkaban och verkar vara ute efter honom.",
                            Genre = "Fantasy",
                            PublishedYear = 1999,
                            Title = "Harry Potter och fången från Azkaban"
                        },
                        new
                        {
                            Id = 8,
                            Author = "J.K. Rowling",
                            Description = "Hogwarts står värd för den magiska trekampen, en farlig tävling mellan tre magiskolor, men Harry blir oförklarligt vald som en fjärde deltagare.",
                            Genre = "Fantasy",
                            PublishedYear = 2000,
                            Title = "Harry Potter och den flammande bägaren"
                        },
                        new
                        {
                            Id = 9,
                            Author = "J.K. Rowling",
                            Description = "Efter Voldemorts återkomst möter Harry misstro från magiministeriet samtidigt som han i hemlighet tränar en grupp elever i försvar mot mörkrets krafter.",
                            Genre = "Fantasy",
                            PublishedYear = 2003,
                            Title = "Harry Potter och Fenixorden"
                        },
                        new
                        {
                            Id = 10,
                            Author = "J.K. Rowling",
                            Description = "Harry och Dumbledore utforskar Voldemorts förflutna för att hitta ett sätt att besegra honom, samtidigt som mörka krafter infiltrerar Hogwarts.",
                            Genre = "Fantasy",
                            PublishedYear = 2005,
                            Title = "Harry Potter och halvblodsprinsen"
                        },
                        new
                        {
                            Id = 11,
                            Author = "J.K. Rowling",
                            Description = "I den sista boken måste Harry, Ron och Hermione hitta och förstöra Voldemorts horrokruxer, vilket leder till en slutgiltig strid om Hogwarts.",
                            Genre = "Fantasy",
                            PublishedYear = 2007,
                            Title = "Harry Potter och dödsrelikerna"
                        },
                        new
                        {
                            Id = 12,
                            Author = "George R.R. Martin",
                            Description = "I kontinenten Westeros kämpar de adliga husen Stark, Lannister och Baratheon om makten över Järntronen efter kungens död.",
                            Genre = "Fantasy",
                            PublishedYear = 1996,
                            Title = "Kampen om järntronen"
                        },
                        new
                        {
                            Id = 13,
                            Author = "George R.R. Martin",
                            Description = "Flera kungar gör anspråk på tronen, vilket leder till ett fullskaligt inbördeskrig samtidigt som ett hot växer i norr bortom muren.",
                            Genre = "Fantasy",
                            PublishedYear = 1998,
                            Title = "Kungarnas krig"
                        },
                        new
                        {
                            Id = 14,
                            Author = "George R.R. Martin",
                            Description = "Kriget i Westeros intensifieras med nya allianser och chockerande svek. Daenerys Targaryen bygger sin armé i öster.",
                            Genre = "Fantasy",
                            PublishedYear = 2000,
                            Title = "Svärdets makt"
                        },
                        new
                        {
                            Id = 15,
                            Author = "George R.R. Martin",
                            Description = "Efter de stora striderna fokuserar boken på maktintrigerna i King's Landing, Järnöarna och Arryns dal.",
                            Genre = "Fantasy",
                            PublishedYear = 2005,
                            Title = "Kråkornas fest"
                        },
                        new
                        {
                            Id = 16,
                            Author = "George R.R. Martin",
                            Description = "Parallellt med händelserna i 'Kråkornas fest' följer denna bok karaktärerna i norr och i öster, inklusive Daenerys och Jon Snow.",
                            Genre = "Fantasy",
                            PublishedYear = 2011,
                            Title = "Drakarnas dans"
                        },
                        new
                        {
                            Id = 17,
                            Author = "J.R.R. Tolkien",
                            Description = "Hobbiten Bilbo Bagger följer med trollkarlen Gandalf och en grupp dvärgar på ett äventyr för att återta sitt hemland från draken Smaug.",
                            Genre = "Fantasy",
                            PublishedYear = 1937,
                            Title = "Hobbiten"
                        },
                        new
                        {
                            Id = 18,
                            Author = "J.R.R. Tolkien",
                            Description = "Bilbos brorson Frodo ärver en magisk ring och får veta att det är Den Enda Ringen, smidd av mörkrets herre Sauron. Han måste föra den till Mordor för att förstöra den.",
                            Genre = "Fantasy",
                            PublishedYear = 1954,
                            Title = "Sagan om ringen"
                        },
                        new
                        {
                            Id = 19,
                            Author = "J.R.R. Tolkien",
                            Description = "Brödraskapet splittras. Frodo och Sam fortsätter mot Mordor, medan deras vänner dras in i kriget mot Sarumans arméer.",
                            Genre = "Fantasy",
                            PublishedYear = 1954,
                            Title = "Sagan om de två tornen"
                        },
                        new
                        {
                            Id = 20,
                            Author = "J.R.R. Tolkien",
                            Description = "Den sista striden om Midgård utkämpas vid Minas Tirith, samtidigt som Frodo och Sam kämpar för att nå Domedagsberget och förstöra Ringen.",
                            Genre = "Fantasy",
                            PublishedYear = 1955,
                            Title = "Sagan om konungens återkomst"
                        },
                        new
                        {
                            Id = 21,
                            Author = "Camilla Läckberg",
                            Description = "Författaren Erica Falck återvänder till Fjällbacka och dras in i utredningen av sin barndomsväns mystiska död, tillsammans med polisen Patrik Hedström.",
                            Genre = "Kriminalroman",
                            PublishedYear = 2003,
                            Title = "Isprinsessan"
                        },
                        new
                        {
                            Id = 22,
                            Author = "Camilla Läckberg",
                            Description = "Erica och Patrik utreder mordet på en ung kvinna vars kropp hittas tillsammans med två äldre skelett, vilket väcker en mörk familjehemlighet till liv.",
                            Genre = "Kriminalroman",
                            PublishedYear = 2004,
                            Title = "Predikanten"
                        },
                        new
                        {
                            Id = 23,
                            Author = "Camilla Läckberg",
                            Description = "En sjuårig flicka hittas drunknad i Fjällbacka, och utredningen leder Patrik och Erica mot en familjetragedi och ett mörkt förflutet.",
                            Genre = "Kriminalroman",
                            PublishedYear = 2005,
                            Title = "Stenhuggaren"
                        },
                        new
                        {
                            Id = 24,
                            Author = "Camilla Läckberg",
                            Description = "En dokusåpa spelas in i Fjällbacka, men när en deltagare mördas måste Patrik Hedström utreda fallet samtidigt som en våldsam olycka drabbar polisstationen.",
                            Genre = "Kriminalroman",
                            PublishedYear = 2006,
                            Title = "Olycksfågeln"
                        },
                        new
                        {
                            Id = 25,
                            Author = "Camilla Läckberg",
                            Description = "Erica Falck utforskar sin mammas förflutna efter hennes död och hittar kopplingar till andra världskriget och ett olöst mord.",
                            Genre = "Kriminalroman",
                            PublishedYear = 2007,
                            Title = "Tyskungen"
                        },
                        new
                        {
                            Id = 26,
                            Author = "Camilla Läckberg",
                            Description = "En man hittas död i sitt hem. Han har tagit emot hotbrev, och Patrik och Erica nystar i ett fall som involverar en försvunnen författare.",
                            Genre = "Kriminalroman",
                            PublishedYear = 2008,
                            Title = "Sjöjungfrun"
                        },
                        new
                        {
                            Id = 27,
                            Author = "Camilla Läckberg",
                            Description = "En kvinna och hennes son flyr till Gråskär, men ön bär på mörka hemligheter. Patrik Hedström utreder ett mord som verkar ha kopplingar till öns fyrvaktare.",
                            Genre = "Kriminalroman",
                            PublishedYear = 2009,
                            Title = "Fyrvaktaren"
                        },
                        new
                        {
                            Id = 28,
                            Author = "Camilla Läckberg",
                            Description = "Ett gammalt fall med en 'änglamakerska' från 1970-talet får ny aktualitet när en serie nya brott med liknande mönster inträffar i Fjällbacka.",
                            Genre = "Kriminalroman",
                            PublishedYear = 2011,
                            Title = "Änglamakerskan"
                        },
                        new
                        {
                            Id = 29,
                            Author = "Camilla Läckberg",
                            Description = "En ung flicka försvinner från en ridskola, och fallet påminner kusligt mycket om ett liknande försvinnande trettio år tidigare.",
                            Genre = "Kriminalroman",
                            PublishedYear = 2014,
                            Title = "Lejontämjaren"
                        },
                        new
                        {
                            Id = 30,
                            Author = "Camilla Läckberg",
                            Description = "Ett fyraårigt flickebarn försvinner, och fallet väcker minnen från ett 30 år gammalt mord på en flicka, vilket skakar om Fjällbacka.",
                            Genre = "Kriminalroman",
                            PublishedYear = 2017,
                            Title = "Häxan"
                        },
                        new
                        {
                            Id = 31,
                            Author = "Camilla Läckberg",
                            Description = "Två brutala mord inträffar i Fjällbacka, och utredningen leder Patrik och Erica mot hemligheter som rör fotografi och konstvärlden.",
                            Genre = "Kriminalroman",
                            PublishedYear = 2022,
                            Title = "Gökungen"
                        },
                        new
                        {
                            Id = 32,
                            Author = "Fredrik Backman",
                            Description = "En humoristisk och rörande berättelse om en vresig änkling som är kvarterets ordningsman, vars liv vänds upp och ner av nya, stökiga grannar.",
                            Genre = "Roman",
                            PublishedYear = 2012,
                            Title = "En man som heter Ove"
                        },
                        new
                        {
                            Id = 33,
                            Author = "Stieg Larsson",
                            Description = "Den första boken i Millennium-serien där journalisten Mikael Blomkvist och hackern Lisbeth Salander utreder ett gammalt försvinnande.",
                            Genre = "Kriminalroman",
                            PublishedYear = 2005,
                            Title = "Män som hatar kvinnor"
                        },
                        new
                        {
                            Id = 34,
                            Author = "George Orwell",
                            Description = "En klassisk roman om ett totalitärt övervakningssamhälle i Oceanien, där Storebror ser allt och historien ständigt skrivs om.",
                            Genre = "Dystopi",
                            PublishedYear = 1949,
                            Title = "1984"
                        },
                        new
                        {
                            Id = 35,
                            Author = "Yuval Noah Harari",
                            Description = "En genomgång av mänsklighetens historia, från de första människorna till de kognitiva, jordbruksmässiga och vetenskapliga revolutionerna.",
                            Genre = "Facklitteratur",
                            PublishedYear = 2011,
                            Title = "Sapiens: En kort historik över mänskligheten"
                        },
                        new
                        {
                            Id = 36,
                            Author = "Vilhelm Moberg",
                            Description = "Den första delen i eposet om Karl Oskar och Kristina och deras resa från ett fattigt Småland till ett nytt liv i Amerika på 1850-talet.",
                            Genre = "Historisk roman",
                            PublishedYear = 1949,
                            Title = "Utvandrarna"
                        },
                        new
                        {
                            Id = 37,
                            Author = "Frank Herbert",
                            Description = "En episk berättelse om maktkamp, politik och religion på ökenplaneten Arrakis, den enda källan till den värdefulla kryddan 'melange'.",
                            Genre = "Science Fiction",
                            PublishedYear = 1965,
                            Title = "Dune"
                        },
                        new
                        {
                            Id = 38,
                            Author = "Delia Owens",
                            Description = "Berättelsen om Kya, 'Träskflickan', som växer upp isolerad i North Carolinas våtmarker och blir misstänkt när en ung man hittas död.",
                            Genre = "Roman",
                            PublishedYear = 2018,
                            Title = "Där kräftorna sjunger"
                        },
                        new
                        {
                            Id = 39,
                            Author = "F. Scott Fitzgerald",
                            Description = "En roman om 1920-talets 'jazz-era', som utforskar teman som dekadens, rikedom och den amerikanska drömmen genom den mystiske miljonären Jay Gatsby.",
                            Genre = "Klassiker",
                            PublishedYear = 1925,
                            Title = "Den store Gatsby"
                        },
                        new
                        {
                            Id = 40,
                            Author = "Paulo Coelho",
                            Description = "En filosofisk berättelse om den andalusiske herdepojken Santiago som följer sin dröm om att hitta en skatt vid Egyptens pyramider.",
                            Genre = "Roman",
                            PublishedYear = 1988,
                            Title = "Alkemisten"
                        },
                        new
                        {
                            Id = 41,
                            Author = "Kazuo Ishiguro",
                            Description = "En gripande berättelse om Kathy H. och hennes vänner från internatskolan Hailsham, där de långsamt upptäcker det mörka syftet med deras existens.",
                            Genre = "Dystopisk roman",
                            PublishedYear = 2005,
                            Title = "Låt mig aldrig gå"
                        },
                        new
                        {
                            Id = 42,
                            Author = "Franz Kafka",
                            Description = "Banktjänstemannen Josef K. blir en morgon arresterad utan att veta vad han anklagas för. Han dras in i en absurd och obegriplig rättsprocess i en labyrintisk byråkrati.",
                            Genre = "Roman",
                            PublishedYear = 1925,
                            Title = "Processen"
                        },
                        new
                        {
                            Id = 43,
                            Author = "Franz Kafka",
                            Description = "Handelsresanden Gregor Samsa vaknar en morgon och upptäcker att han har förvandlats till en jättelik insekt, vilket får fruktansvärda konsekvenser för honom och hans familj.",
                            Genre = "Kortroman",
                            PublishedYear = 1915,
                            Title = "Förvandlingen"
                        },
                        new
                        {
                            Id = 44,
                            Author = "Franz Kafka",
                            Description = "En man känd som 'K.' anländer till en by för att arbeta som lantmätare åt det lokala slottet, men han kämpar förgäves mot en oåtkomlig byråkrati för att ens få sitt uppdrag bekräftat.",
                            Genre = "Roman",
                            PublishedYear = 1926,
                            Title = "Slottet"
                        },
                        new
                        {
                            Id = 45,
                            Author = "Franz Kafka",
                            Description = "Den unge Karl Rossmann skickas till Amerika av sina föräldrar. Romanen skildrar hans pikareskartade och ofta surrealistiska resa genom det främmande landet.",
                            Genre = "Roman",
                            PublishedYear = 1927,
                            Title = "Amerika (Den försvunne)"
                        });
                });

            modelBuilder.Entity("BookReview.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("BookId_FK")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("ReviewerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId_FK = 1,
                            CreatedDate = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            ReviewerName = "Alice Andersson",
                            Text = "Otroligt gripande bok – kunde inte sluta läsa!"
                        },
                        new
                        {
                            Id = 2,
                            BookId_FK = 2,
                            CreatedDate = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4,
                            ReviewerName = "Björn Berg",
                            Text = "Riktigt spännande, men lite förutsägbar på slutet."
                        });
                });

            modelBuilder.Entity("BookReview.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "alice@example.com",
                            Name = "Vicke Andersson",
                            PasswordHash = "hash123",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bjorn@example.com",
                            Name = "Björn Berg",
                            PasswordHash = "hash456",
                            Role = "User"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "clara@example.com",
                            Name = "Anders Hertig",
                            PasswordHash = "hash789",
                            Role = "User"
                        });
                });

            modelBuilder.Entity("BookReview.Models.Review", b =>
                {
                    b.HasOne("BookReview.Models.Book", "Book")
                        .WithMany("Reviews")
                        .HasForeignKey("BookId");

                    b.HasOne("BookReview.Models.User", null)
                        .WithMany("Reviews")
                        .HasForeignKey("UserId");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("BookReview.Models.Book", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("BookReview.Models.User", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
